# QuickBanUI Configuration
# Version: 2.0
# Author: MrCappy

# ======================
# General Settings
# ======================
settings:
  # Broadcast punishments to staff with quickban.notify permission
  broadcast-punishments: true

  # Log all punishments to console
  log-to-console: true

  # Date format for logs and history
  date-format: "yyyy-MM-dd HH:mm:ss"

  # Appeal link shown in ban messages (leave empty to disable)
  appeal-link: "discord.gg/yourserver"

  # Commands blocked while muted
  mute-blocked-commands:
    - "tell"
    - "msg"
    - "w"
    - "whisper"
    - "r"
    - "reply"
    - "me"
    - "say"

# ======================
# MySQL Database
# ======================
mysql:
  enabled: false
  host: "localhost"
  port: "3306"
  database: "quickbanui"
  username: "root"
  password: "password"
  # Server name for multi-server setups
  server-name: "Server-1"

# ======================
# Discord Integration
# ======================
discord:
  # Enable Discord webhook notifications
  enabled: false

  # Discord webhook URL
  webhook-url: ""

  # Bot username in Discord
  username: "QuickBanUI"

  # Avatar URL for the bot
  avatar-url: "https://i.imgur.com/example.png"

  # Footer icon URL
  footer-icon: ""

  # Show server name in embeds
  show-server: true

  # Server name to display
  server-name: "My Server"

# ======================
# GUI Settings
# ======================
gui:
  # Items per page in history GUI
  history-items-per-page: 45

  # Fill empty slots with glass panes
  fill-empty-slots: true

  # Material for empty slots
  filler-material: GRAY_STAINED_GLASS_PANE

  # Show player heads in GUIs
  show-player-heads: true

# ======================
# Punishment Reasons
# ======================
# Customize quick-select reasons for each punishment type
punishment-reasons:
  ban:
    - "Hacking"
    - "Griefing"
    - "Ban Evasion"
    - "Exploiting"
    - "Severe Toxicity"
    - "Scamming"

  mute:
    - "Spamming"
    - "Toxicity"
    - "Advertising"
    - "Excessive Caps"
    - "Inappropriate Language"
    - "Harassment"

  kick:
    - "AFK"
    - "Inappropriate Behavior"
    - "Server Full"
    - "Restart Required"
    - "Flying/Hacking"
    - "Warning"

  warn:
    - "Minor Rule Violation"
    - "Inappropriate Language"
    - "Disrespectful Behavior"
    - "Building Violation"
    - "Chat Violation"
    - "First Offense"

# ======================
# Reason Materials
# ======================
# Materials for reason items in GUI
reason-materials:
  ban:
    - BARRIER
    - TNT
    - LAVA_BUCKET
    - NETHERITE_SWORD
    - WITHER_SKELETON_SKULL
    - END_CRYSTAL

  mute:
    - PAPER
    - BOOK
    - WRITABLE_BOOK
    - NAME_TAG
    - OAK_SIGN
    - BELL

  kick:
    - LEATHER_BOOTS
    - IRON_BOOTS
    - GOLDEN_BOOTS
    - DIAMOND_BOOTS
    - NETHERITE_BOOTS
    - ELYTRA

  warn:
    - YELLOW_DYE
    - YELLOW_BANNER
    - GOLD_INGOT
    - BELL
    - GLOWSTONE
    - YELLOW_WOOL

# ======================
# Duration Settings
# ======================
durations:
  # Available duration options
  options:
    - "5m"
    - "10m"
    - "30m"
    - "1h"
    - "2h"
    - "6h"
    - "12h"
    - "1d"
    - "3d"
    - "7d"
    - "14d"
    - "30d"
    - "60d"
    - "90d"
    - "permanent"

  # Default duration for each type
  defaults:
    ban: "7d"
    mute: "1h"

# ======================
# Permission Settings
# ======================
permissions:
  # Max duration for each permission group (in days, -1 for unlimited)
  max-duration:
    helper: 1
    moderator: 30
    admin: -1

  # Can use permanent punishments
  permanent:
    helper: false
    moderator: false
    admin: true

# ======================
# Advanced Settings
# ======================
advanced:
  # Auto-save interval in minutes (0 to disable)
  auto-save-interval: 5

  # Maximum custom reason length
  max-reason-length: 100

  # Punishment cooldown in seconds (prevent spam)
  punishment-cooldown: 3

  # Check for expired punishments every X seconds
  expiry-check-interval: 20

  # Enable debug messages
  debug: false