name: QuickBanUI
version: 2.0
main: net.mrcappy.quickbanui.QuickBanUI
api-version: 1.19
author: MrCappy
description: A simple and intuitive punishment GUI plugin for Minecraft servers
website: https://github.com/MrCappy/QuickBanUI

commands:
  punish:
    description: Open the punishment GUI for a player
    usage: /<command> <player>
    aliases: [p]

  ban:
    description: Ban a player using the GUI
    usage: /<command> <player>

  mute:
    description: Mute a player using the GUI
    usage: /<command> <player>

  kick:
    description: Kick a player using the GUI
    usage: /<command> <player>

  warn:
    description: Warn a player using the GUI
    usage: /<command> <player>

  unban:
    description: Unban a player
    usage: /<command> <player>

  unmute:
    description: Unmute a player
    usage: /<command> <player>

  history:
    description: View a player's punishment history
    usage: /<command> <player>
    aliases: [hist]

  qb:
    description: QuickBanUI admin command
    usage: /<command> [reload|analytics|reasons|backup|update]
    aliases: [quickban, quickbanui]

permissions:
  quickban.punish:
    description: Allows access to the main punishment GUI
    default: op

  quickban.ban:
    description: Allows banning players
    default: op

  quickban.mute:
    description: Allows muting players
    default: op

  quickban.kick:
    description: Allows kicking players
    default: op

  quickban.warn:
    description: Allows warning players
    default: op

  quickban.unban:
    description: Allows unbanning players
    default: op

  quickban.unmute:
    description: Allows unmuting players
    default: op

  quickban.history:
    description: Allows viewing punishment history
    default: op

  quickban.notify:
    description: Receive punishment notifications
    default: op

  quickban.exempt:
    description: Exempt from being punished
    default: false

  quickban.silent:
    description: Allows silent punishments
    default: op

  quickban.admin:
    description: Access to admin commands
    default: op